### ISSUE TITLE
Return mapped model instance after any graphql query

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1009]
Have the execute function map the array data to the proper model class based on the `GraphQuery.type`.
```
async execute() {
    const query = this.build();
    // Post query to window
    if (!isProduction()) {
      window.queries += `\n${query}`;
    }

    const res = await client.query({
      query: gql`${query}`,
      fetchPolicy: 'network-only',
    });
    return res.data[this.queryName]; // map the data to the proper model
  }
```

**Comment by ippudo** [comment]
- [allTopics(...)] 
- [allOracles(...)] 
- [searchTopics(...)] 
- [searchOracles(...)] 
- [allVotes(...)] 
- [resultSets(...)] 
- [withdraws(...)] 
- [allTransactions(...)] 
- [syncInfo(...)] 
- [addressBalances]

**Comment by dwalintukan** [comment]
Don't worry about  Votes, Result Sets, and Withdraws. Don't think we query those yet.

**Comment by ippudo** [comment]
#1010
