### ISSUE TITLE
When switch to a new wallet, transactions cached for ExecuteTxDialog remains to be previous one's

### ISSUE THREAD

**Issue by ippudo** [bodhiproject/bodhi-ui#1021]
And you still can send these transactions, then it will appeared as the activity history of previous wallet's.

**Comment by ippudo** [comment]
We still need to handle the following flow:

Wallet A -> Bet -> close Transaction confirm dialog -> change to Wallet B -> the Bet transaction from A still at the confirm dialog

**Comment by dwalintukan** [comment]
#1034
