### ISSUE TITLE
Remove scrollbar and increase Create Event dialog width

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1036]
The width is smaller than it was before. Looks scrunched up. Make it wider like it was before.

![image](https://user-images.githubusercontent.com/4350404/46523598-66d78600-c8b0-11e8-938a-f4b6880aee11.png)

**Comment by dwalintukan** [comment]
think we can just remove the scrollbar entirely? might look better without it.

**Comment by BernardHan** [comment]
@dwalintukan if no scroll, we can use scroll='body', so when the height is not enough, the user will scroll the whole dialog instead of scrolling inside the dialog. The margin gets all wrong tho.
https://material-ui.com/demos/dialogs/
Check the last demo.

Do you want me to do it?

**Comment by dwalintukan** [comment]
Ya I played around with it before. If you can get the margins right with scroll body I say go for it. 

This thread talks about it:
https://github.com/mui-org/material-ui/issues/10000

Native CSS trick:
https://stackoverflow.com/a/16671476/2917742
