### ISSUE TITLE
Create Event popup descriptions for each field

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1044]
Need better explanations about each field in the Create Event modal.

**Comment by lillland** [comment]
To avoid showing too many small texts and question marks, show description when users hover on each title.
<img width="686" alt="screen shot 2018-10-23 at 3 44 55 pm" src="https://user-images.githubusercontent.com/5739162/47395522-df757980-d6db-11e8-8f42-cff7e886666c.png">

**Comment by dwalintukan** [comment]
👍
