### ISSUE TITLE
Leaderboards

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1060]
1. Who Bet the Most QTUM? - in all detail pages (this should be total cumulation of all QTUM bets per address)
2. Who Voted the Most BOT? - in all detail pages (total cumulation of all BOT votes per address)
3. Biggest Winners - in Withdraw detail only

https://www.figma.com/file/ChDp3DmTpPvcA8nrvpc6dgFK/Bodhi-App-UI?node-id=179%3A431

In mobile size, make sure table is horizontally scrollable.

**Comment by ippudo** [comment]
Did Henry assign himself for this task last week?

**Comment by dwalintukan** [comment]
Don't think so. We will assign this as part of tomorrow's sprint.

**Comment by henryzbw** [comment]
@dwalintukan how do we consider the biggest winner? most amounts or return rate? and for qtum or for bot?

**Comment by henryzbw** [comment]
and how many entries do we show in the leaderboard, thinks 20 is too much, maybe 5?

**Comment by henryzbw** [comment]
#1066
