### ISSUE TITLE
Bet button is enabled when it shouldn't be

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1070]
The CTA button should be disabled here but its enabled and I can click it which leads to a bug.

![image](https://user-images.githubusercontent.com/4350404/47334393-f05cc580-d6b0-11e8-93be-834afb9a4db8.png)

**Comment by ippudo** [comment]
Is there any further information to trigger this bug?

**Comment by dwalintukan** [comment]
@ippudo All I did was go on dev.puti.io and click on an event in Qtum Prediction. Make sure qrypto is logged out.

**Comment by ippudo** [comment]
Need to confirm whether it is fixed in the latest master branch.

**Comment by dwalintukan** [comment]
Confirmed fixed
