### ISSUE TITLE
Trigger Naka Wallet popup

### ISSUE THREAD

**Issue by BernardHan** [bodhiproject/bodhi-ui#1116]

**Comment by BernardHan** [comment]
https://medium.com/metamask/https-medium-com-metamask-breaking-change-injecting-web3-7722797916a8

Use `window.etheruem.enable()`

Need to checkon if loggedin or not

**Comment by BernardHan** [comment]
Problem is that `window.etheruem` would trigger both metamask and naka wallet.

Need to discuss more with @dwalintukan 

Other issues are more important, will come back later.

**Comment by dwalintukan** [comment]
@BernardHan will need to handle this case later. Don’t worry about it now since we are using an older forked version where it is auto injected.
