### ISSUE TITLE
Refine event card by learning from guesser.io

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#1238]
![IMG_9576](https://user-images.githubusercontent.com/711206/58451617-0ad4a280-80c9-11e9-90e7-3717ba82c1cb.PNG)
![IMG_9581](https://user-images.githubusercontent.com/711206/58451618-0ad4a280-80c9-11e9-81b6-14079a10ca90.PNG)

**Comment by henryzbw** [comment]
![IMG_3257](https://user-images.githubusercontent.com/10339131/58520940-1aa6c200-816f-11e9-9412-f0bbd58985d5.jpg)
