### ISSUE TITLE
Event Result Setting should be named Oracle Result Setting

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1302]
![image](https://user-images.githubusercontent.com/4350404/58682630-8d948080-839b-11e9-9d6e-5fe423fb30a3.png)

**Comment by TT1943** [comment]
I think the current wording is correct

**Comment by dwalintukan** [comment]
We have two result setting states: Oracle Result Setting and Open Result Setting. Oracle referring to the Centralized Oracle user.

**Comment by TT1943** [comment]
@dwalintukan I know. Let's don't distinguish them for now. If it is still confusing, I am going to figure out a better way instead of just changing a name
