### ISSUE TITLE
Based on period length, show different color for each vertical line

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#1337]
![image](https://user-images.githubusercontent.com/711206/58781655-5edffb00-8591-11e9-9f6b-5d37cdb3ff80.png)
Title: Estimated Result Finalized Date (预计结果揭晓时间）
Value：Show the Result Setting Ending Date instead.

**Comment by henryzbw** [comment]
![image](https://user-images.githubusercontent.com/10339131/59136267-2fd1dc80-8937-11e9-8240-8d362ac223c4.png)

**Comment by TT1943** [comment]
![image](https://user-images.githubusercontent.com/711206/59578277-53ee9580-907c-11e9-8ce7-9d5fa9e852ec.png)
