### ISSUE TITLE
Enable Naka Name Service in Bodhi

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#1346]
Depends on:
https://github.com/bodhiproject/bodhi-server/issues/272

- [ ] Create a reusable component to handle if the address has a name attached to it
- [ ] Create model for `Address` that contains address and name (could prob combine it to hold balances too)

**Comment by dwalintukan** [comment]
Depends on:
https://github.com/bodhiproject/bodhi-server/issues/272
