### ISSUE TITLE
ui issues from users

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#1438]
![IMG_9775](https://user-images.githubusercontent.com/711206/59391033-e9f68900-8d27-11e9-9efa-e32f56320e1e.JPG)
时间超过10：12还能bet

![IMG_9776](https://user-images.githubusercontent.com/711206/59391034-e9f68900-8d27-11e9-860c-717cd97e13bf.JPG)
总投注错误

![IMG_9777](https://user-images.githubusercontent.com/711206/59391035-e9f68900-8d27-11e9-9e38-aa208ec06cf3.JPG)
数量应该全部完整，包括小数点

![IMG_9778](https://user-images.githubusercontent.com/711206/59391036-e9f68900-8d27-11e9-8685-7000a0b6e0b2.JPG)
【暂时忽视】回报计算规则

![IMG_9779](https://user-images.githubusercontent.com/711206/59391037-e9f68900-8d27-11e9-9242-d3e407cb243b.JPG)
数量显示不对，应该用数量缩略版

![IMG_9780](https://user-images.githubusercontent.com/711206/59391038-e9f68900-8d27-11e9-9edc-f8e06a3f9273.PNG)
信息显示不全，数量应该显示缩略版

![IMG_9781](https://user-images.githubusercontent.com/711206/59391039-eb27b600-8d27-11e9-8953-8db05da18c90.JPG)
数量应该显示完整格式

![IMG_9767](https://user-images.githubusercontent.com/711206/59391040-eb27b600-8d27-11e9-9cb9-72166570b123.PNG)
字体出框

**Comment by henryzbw** [comment]
数量应该显示缩略版 take
