### ISSUE TITLE
Next Plan

### ISSUE THREAD

**Issue by BernardHan** [bodhiproject/bodhi-ui#1522]
![image](https://user-images.githubusercontent.com/23019256/59944107-cc58ac00-9418-11e9-864a-348106be147f.png)

Features & Improvements (Ordered by priority)
1. Loading too slow, optimize performance (done)
2. Make another leaderboard for percentage of `# of winning / # of invested`
3. Make leaderboard show by day, week, month, year and all
4. Improvement and tweek create event page and event detail page, eg. side bar #1432 
5. Remove exceeding margins
6. Make filter options in prediction, arbitration, all event pages (on hold)
7. Implement account feature, click on address go to profile page, showing name, avatar, recent activities (on hold)
8. Leaderboard shows all recent activities

**Comment by henryzbw** [comment]
removeing exceeding margins now
