### ISSUE TITLE
Remove calculateWinnings and getDidWithdraw requests every 5 blocks

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1531]
This is getting too spammy for the server. Please change the following logic:
- Call `calculateWinnings` only once when the user enters the Event detail page
- If this fails, then you can do a repeating request like every 5 or 10 seconds until you receive a valid response. Also handle the UI portion of this too, if the request failed the first time, show some sort of spinner or message "Calculating Winnings, Please Wait" in place where the winnings are supposed to be.
- We only need to calculate winnings once since it won't change since the event is done
- Do the same with `didWithdraw`. We don't need to repeatedly know that they have already withdrawn. 
- If the user didn't withdraw yet and withdraws, then you can do the repeating request until you receive a valid response.

**Comment by BernardHan** [comment]
What happens currently is that if the event page is in withdraw, `calculateWinnings` and `didWithdraw` will be called in `initEvent`. And will never be called again unless:

1. user goes from offline to online
2. there're pending txs, which is not likely if it's in withdraw phase

In the two methods, you did add the line if the block number cannot divided by 5 fully, then return.
But this line has no effect after we remove all pulling data on new block.

I think this issue can be closed.

**Comment by dwalintukan** [comment]
Got it. Hm must have been multiple people calling it then. Closing.
