### ISSUE TITLE
When you click a result for betting, there is no way to go back to "detail page" before betting

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#196]
![image](https://user-images.githubusercontent.com/711206/37087170-5d70f85c-21ae-11e8-8e57-85f7f37e0030.png)

**Comment by liviavinci** [comment]
this is missing a close button (but actually you can go back after clicking on the blank space right now)

**Comment by liviavinci** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/272
