### ISSUE TITLE
Click on betting button show an error page

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#197]
First I see
![image](https://user-images.githubusercontent.com/711206/37087203-78685d62-21ae-11e8-9f6a-a535b70aad8a.png)

Then after I click "ok", I see
![image](https://user-images.githubusercontent.com/711206/37087211-8116a284-21ae-11e8-9e69-93b81035565a.png)

**Comment by dwalintukan** [comment]
#216
