### ISSUE TITLE
Cannot withdraw

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#204]
I have 4 addresses in my app. I tried to withdraw 200 BOT from `qaeu2kdcDEacQY3pxqZN6hU3Teiwj8Eo3o` to `qgDsVpjXHBnpsovbaQ6J2tsE8rtqvzvrmK`. But it doesn't work

![image](https://user-images.githubusercontent.com/711206/37093960-13ed5b04-21c6-11e8-9cbf-7286a15def00.png)

**Comment by TT1943** [comment]
And I receive the following error message
![image](https://user-images.githubusercontent.com/711206/37094043-5d2a7d1a-21c6-11e8-90e5-8f6bb6deea53.png)

**Comment by dwalintukan** [comment]
fixed, pending transactions now show in the Transfer History
