### ISSUE TITLE
Currently no pop up to unlock wallet

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-ui#21]

**Comment by chrisli30** [comment]
Not an issue for unencrypted walllet

**Comment by dwalintukan** [comment]
Need this before release

**Comment by liviavinci** [comment]
What does this issue mean?

**Comment by dwalintukan** [comment]
Qtum wallets that are encrypted (which you should do for real money),  need to be unlocked with a wallet passphrase when you want to do a tx. This will require a dialog pop up saying "Please enter your wallet passphrase", then we will unlock the wallet and exec the tx. @liviavinci

**Comment by dwalintukan** [comment]
#259
