### ISSUE TITLE
my activities & copy wallet address & time zone

### ISSUE THREAD

**Issue by janebodhi** [bodhiproject/bodhi-ui#226]
1. nothing showed up when I clicked "my activities", when I created an event (in pending) status.
<img width="780" alt="screen shot 2018-03-08 at 4 48 07 pm" src="https://user-images.githubusercontent.com/37197997/37184526-99c2c324-22f0-11e8-8ec7-67c39ff66d18.png">

2. In setting block time, is there a way to mark  "-07:00" in  "2018-03-15 16:50:56 -07:00" as time zone? otherwise it is very confusing. 

3. During the event set-up process. When I was trying to set the centralized oracle, I'll need to copy my wallet address, and I found everything I input for the event setup disappeared.

**Comment by TT1943** [comment]
These are three different issues. For 3, I propose to store event creation data while editing. This will solve many problems and make it user friendly

**Comment by dwalintukan** [comment]
@janebodhi 
1. just finished the logic to show a newly created Event today. please note that this unconfirmed (unconfirmed meaning not mined/created yet) Event will only show up in the `QTUM Prediction` tab as it will be in the betting stage. We don't have a tab in `My Activities` that accurately reflects the state that an unconfirmed Event is in. What will happen is, when you create a new Event in the `Create an Event page`, after creating it, it will route you back to the `QTUM Prediction` dashboard where you will see your unconfirmed Event.

2. are you referring to the date/time picker? We have it set to the local timezone right now. Are you saying you want it to display as UTC timezone?

3. We are going to add an address picker for the Centralized Oracle field in the Create Event page.

**Comment by lillland** [comment]
For 1
![minieventcard_normal copy 5](https://user-images.githubusercontent.com/5739162/37498005-ef462466-2878-11e8-860e-6d2407512ae5.png)

**Comment by dwalintukan** [comment]
done #328
