### ISSUE TITLE
Chinese for BOT Court and QTUM Prediction?

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#237]

**Comment by TT1943** [comment]
我们故意叫Qtum Prediction和BOT court是为了提示用户做对赌预测时只能用qtum，做仲裁时只能用BOT，不需要叫仲裁法庭

**Comment by frankobe** [comment]
@liviavinci  as TT explained, lets insist to QTUM Prediction and BOT Court

**Comment by liviavinci** [comment]
Wanna help me think of a translation for these two?

**Comment by liviavinci** [comment]
@frankobe @TT1943
