### ISSUE TITLE
Should we call 我的活动/我的事件？My Activites/My Events?

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#238]

**Comment by TT1943** [comment]
建议：我的活动，My Activities

**Comment by frankobe** [comment]
@liviavinci 我的活动，My Activities. Let's try avoid using events as they are referred as 'prediction events'

**Comment by dwalintukan** [comment]
Also, My Activities also includes the Activity History so not completely accurate in terms of calling it My Events.
