### ISSUE TITLE
Show “wait” message if there is transaction of mine pending for this oracle

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#245]

**Comment by dwalintukan** [comment]
@liviavinci is this suitable enough for now? can add a better text style when the different style of alerts is created.

![image](https://user-images.githubusercontent.com/4350404/37276743-38ed63ce-2615-11e8-9b47-05be49e4710a.png)

**Comment by dwalintukan** [comment]
#221
