### ISSUE TITLE
Use personal amount info instead of the total info for withdraw page

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#273]
<img width="810" alt="screen shot 2018-03-13 at 2 42 32 pm" src="https://user-images.githubusercontent.com/1126827/37327365-f8593f4c-26d0-11e8-9968-aa69686fa2f0.png">

**Comment by liviavinci** [comment]
Also the withdraw page button is not properly disabled

**Comment by dwalintukan** [comment]
#280
