### ISSUE TITLE
Fix routing of clicking `View Event` from Activity History

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#289]
Clicking `View Event` of a past tx will route to a bad page if the Event is not in the same stage as that tx.

ie.
- You Vote on an Oracle
- You see your Vote in the tx history, but that Oracle has already passed the threshold and there is a new Oracle
- If you click on View Event, it will try to route to the already done Oracle and show a blank page

When clicking View Event, should make a BE call and figure out what stage it is in and route to the correct page.

**Comment by liviavinci** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/290
