### ISSUE TITLE
Show rich info on blockchain data downloading

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#292]
1. We need to describe why we need to download the whole blockchain data (because we are fully running on blockchain)
2. We need to show rich info such as block number left, estimated time, network speed, so that users fully understand the current status, refer qtum wallet downloading for example.
![image](https://user-images.githubusercontent.com/711206/37429746-7b1c7b12-278d-11e8-9dfb-d80dfe9cba26.png)

**Comment by lillland** [comment]
![artboard](https://user-images.githubusercontent.com/5739162/37687878-8e3d8854-2c5a-11e8-8fe3-330f8982983f.png)

**Comment by liviavinci** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/458
