### ISSUE TITLE
Inconsistent between count and real content

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#293]
In my activities, the count for each tab is inconsistent, for example, result setting show `2`, but actually there are `6` see image below. NOTE that, we should only list events that users have permission to set the result. 
![image](https://user-images.githubusercontent.com/711206/37429956-104d062a-278e-11e8-83cd-21152616dead.png)

`3` in Withdraws, but actually there are `4` events:
![image](https://user-images.githubusercontent.com/711206/37430119-75295e04-278e-11e8-9b46-b7cb95b642b4.png)

**Comment by dwalintukan** [comment]
@TT1943 the badge number in the top left and on the tabs is the count of the items that the user himself can do. I don't agree that we should hide any items that the user can't set the result for example. 

For example, if this user already bet on that event but he's not the result setter and it's not showing up on the Result Setting tab, then this user will freak out after he knows he bet on an event but can't see it.

**Comment by liviavinci** [comment]
The count is for the actionable events, and dashboard shows the complete event list so user can always check on the events that they are interested in. I know it's a bit confusing for now but the problem will be solved when bookmark feature is out.

**Comment by TT1943** [comment]
Hey, as I said in our meeting last time, users are able to review all participated events from activities list. Please hide non-related events from this

**Comment by dwalintukan** [comment]
This is fixed in the same PR as the escrow staking. Which is not merged in master yet.

**Comment by frankobe** [comment]
@dwalintukan pr reference needed and @TT1943 can u close it after verification
