### ISSUE TITLE
Deposited balance is not shown

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#296]
As you can see from the transfer history, the `two` BOT transfers are successful. Actually, I transfer from `qYqDQBKU7csFBdPSbUiYEdurjxBpNwPPHm` (my own address) to two other my own addresses: `qVB2f1rmpjUuCCMm8xBv9ubGunArxMhiaG` and `qTsqKfgZW3hTkTbxgzBg6qjTqbTZNhrHwa`. The BOT was correctly substracted from the sender addresses, but not correctly added to the two of my own addresses. 
![image](https://user-images.githubusercontent.com/711206/37430546-a4d66470-278f-11e8-90e0-d842f6063212.png)

**Comment by dwalintukan** [comment]
#330
