### ISSUE TITLE
event card need to show different color for different status

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#297]
We need to use different color/style to indicate that a event is (pending for creation, pending for betting, pending for finalizing, etc)

**Comment by dwalintukan** [comment]
@lillland @lukaning Can you please provide for us the colors as requested? Thanks.

**Comment by lillland** [comment]
add a label on the card to indicate the status. 
<img width="296" alt="screen shot 2018-03-20 at 4 18 01 pm" src="https://user-images.githubusercontent.com/5739162/37687828-525c4622-2c5a-11e8-9122-c4135902970b.png">

**Comment by liviavinci** [comment]
@dwalintukan @TT1943 is this the same thing as in https://github.com/bodhiproject/bodhi-ui/issues/443? if so i'm gonna merge these two.

**Comment by dwalintukan** [comment]
@liviavinci I believe they are the same. Either that or we need to get some insight from designers.

**Comment by liviavinci** [comment]
@lillland can you specify the scope of this?

**Comment by dwalintukan** [comment]
@alex-cory let's show `Pending Confirmation` for:
1. Pending Bet
2. Pending Set Result
3. Pending Vote
4. Pending Finalize
5. Pending Withdraw
