### ISSUE TITLE
After I finalize an event, the description says I have withdrawn from this event

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#298]
I think there is some bug in determining the description:
![image](https://user-images.githubusercontent.com/711206/37433887-eb646256-279a-11e8-99ac-a8337f9f65f1.png)

**Comment by dwalintukan** [comment]
Just tested, cannot repro currently. Will reopen if observed again.

**Comment by dwalintukan** [comment]
Was able to repro the bug. Fixed in #342
