### ISSUE TITLE
Transfer History missing incoming deposit transaction history

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#301]
Some one send me 2 QTUM to my address `qTsqKfgZW3hTkTbxgzBg6qjTqbTZNhrHwa`, I do receive it, but there is no deposit transaction hisotry in Transfer History

**Comment by dwalintukan** [comment]
Ya for the first transaction history we aren't parsing incoming transfers from outbound addresses. We aren't parsing `Transfer` events in the BE yet. We were planning to add this in one of the next iterations.

**Comment by dwalintukan** [comment]
Going to create a ticket for this for future enhancement.

**Comment by dwalintukan** [comment]
https://github.com/bodhiproject/bodhi-graphql/issues/147
