### ISSUE TITLE
change transparent App Icon to solid 

### ISSUE THREAD

**Issue by lillland** [bodhiproject/bodhi-ui#303]
![logo for app](https://user-images.githubusercontent.com/5739162/37441147-24586b44-27bd-11e8-960b-54b325408207.png)

img link: https://drive.google.com/open?id=1klGYUKRTd7yh74xgCbzY0Vuj3i_1WCci

**Comment by dwalintukan** [comment]
@lillland I need this in 512 x 512 please

**Comment by dwalintukan** [comment]
done
