### ISSUE TITLE
Transaction created 7 days ago is still pending till now

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#305]
![image](https://user-images.githubusercontent.com/711206/37442211-3c8040fc-27c2-11e8-9694-bf658db84e5a.png)

**Comment by dwalintukan** [comment]
@TT1943 I think you have a bugged UTXO like me. Can you send me the txid?

**Comment by dwalintukan** [comment]
@TT1943 this seems to be an issue with qtum wallet itself. I just tested and seems like if you send it to one of your addresses you own then the tx itself stays pending.

**Comment by dwalintukan** [comment]
#376 duplicate
