### ISSUE TITLE
Check balance before make transaction

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#307]
Before we make any transaction, we need to check the available balance.
For example, when user bet/finalize, check whether the address he pick has enough QTUM that he specifies before actually make transaction. When user vote, check whether the address he picks has enough QTUM for paying transaction fee and enough BOT that he specifies for voting.
If not enough balance, we need to show a pop up windows.

**Comment by dwalintukan** [comment]
@TT1943 This is already in there. Please note that QTUM balance check is using the entire wallets balance, not just the individual address. This is how the qtum wallet operates to. You can spend from any address up to the total amount.

BOT balance check is based on the selected address.

**Comment by dwalintukan** [comment]
Related to #309. Also we already handle the checks.
