### ISSUE TITLE
Bet: Display a dialog to explain if we are using money from more than the selected address

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#309]
This is unbelievable, I made two transaction from two addresses that have less then 10 QTUM, then I bet one 10 QTUM, one 100 QTUM, both are successful. See picture below
![image](https://user-images.githubusercontent.com/711206/37445925-c6191536-27d7-11e8-9e58-6a134858108f.png)

step 1.
![image](https://user-images.githubusercontent.com/711206/37445938-dfb1a1ca-27d7-11e8-9076-33d4af5f7344.png)

Step 2.
Transaction ID: 843f4b77d3b541857731c12188ccc1ab085f13f026d5d1037f9700e7021338e0
![image](https://user-images.githubusercontent.com/711206/37445950-ead66252-27d7-11e8-85d4-a714cfada5c4.png)

Step 3. before the tx gets confirmed, the choice I set is still `0 QTUM`, and the tx is `pending`
![image](https://user-images.githubusercontent.com/711206/37445963-fa0ac330-27d7-11e8-90fa-e7ad4b526086.png)

![image](https://user-images.githubusercontent.com/711206/37445971-ff3d81bc-27d7-11e8-958a-aa292af737a6.png)

Step 4. after the tx gets confirmed, the choice shows `100 QTUM`, and the tx is `success`:
![image](https://user-images.githubusercontent.com/711206/37446002-23259254-27d8-11e8-821b-6bde506afbce.png)

![image](https://user-images.githubusercontent.com/711206/37446012-2a5c70ec-27d8-11e8-9cc3-3d5586256229.png)

Step 5. I thought this is temporary result. However, after I restart, the result is still the same:
![image](https://user-images.githubusercontent.com/711206/37446150-d60054a4-27d8-11e8-8951-ec0ab2965969.png)

![image](https://user-images.githubusercontent.com/711206/37446151-da0799a4-27d8-11e8-9833-f56b446f6144.png)

Step 5. If you check your wallet, the balance does get subtracted, (looks like from other addresses, not the the address I specified above), looks like 0 balance addresses are hidded? I used to have more than 4 addresses:
![image](https://user-images.githubusercontent.com/711206/37446198-fba770ca-27d8-11e8-9ea4-8e65c74675e9.png)

**Comment by liviavinci** [comment]
Holy x

**Comment by liviavinci** [comment]
@TT1943 remember to tag the bi-weekly project when creating an issue

**Comment by dwalintukan** [comment]
this is not a bug. this is how our system works. we chose not to add cached pending txs.

**Comment by TT1943** [comment]
@liviavinci ok, was thinking that you guys are organizing these bugs

**Comment by TT1943** [comment]
@dwalintukan please read the whole step, `not adding cached pending txs` is correct, but it is confirmed successfully later on, and the QTUM are charged from other addresses, not the one I specified.

**Comment by liviavinci** [comment]
@dwalintukan but didn't we already disable the bet button when there isn't enough qtum?

**Comment by dwalintukan** [comment]
@TT1943 that is how QTUM wallet works. if you have 100 QTUM spread over 100 different UTXOs with all different addresses you can still spend up to that 100 QTUM even though it is in different addresses. you own all the addresses. this is how QT Wallet works too. we shouldn't change the spending mechanism for the wallet

**Comment by dwalintukan** [comment]
this seems to be bad UX in that we should let the user know they can spend UP TO the TOTAL QTUM balance. the only reason we select addresses when betting is for the smart contract purposes (to know who bet).

**Comment by liviavinci** [comment]
@dwalintukan i see now. i think we should display a dialog explaining this if we are using money from more than the selected address.

**Comment by dwalintukan** [comment]
@liviavinci Agreed. It might be confusing since QTUM uses the wallet total, and BOT uses the address total.

**Comment by TT1943** [comment]
@dwalintukan I understand this. But the question is: in this case, are the amount of QTUM from multiple addresses now is betted under the name of specified address? If the bet is correct, will user be able to withdraw the bet and reward through the specified address, or they have to withdraw it from multiple addresses? Please help to test this carefully.

**Comment by dwalintukan** [comment]
@TT1943 The bet will come entirely from the sender address, which is picked when you make the bet. So you will only need to withdraw from that single address.

**Comment by TT1943** [comment]
@dwalintukan ok. Please make sure it is verified that this is the case.
