### ISSUE TITLE
[Future] System topic blacklist, user topic blacklist

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#311]
We are going to have two blacklists in the future:
System blacklist: we update it timely whenever we think there are some topics that are not suitable for users. Topic in system blacklist won't be visible/accessible for all users who are using our app with that versions and above.
User topic blacklist: user is able to hide certain topic that they are not comfortable with (put into the user topic blacklist). user is able to access this blacklist through some entrance and recover some topics back.

**Comment by dwalintukan** [comment]
Created BIP
