### ISSUE TITLE
Transaction history not complete

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#312]
<img width="1440" alt="screen shot 2018-03-15 at 2 04 27 pm" src="https://user-images.githubusercontent.com/1126827/37447009-c6eaafe6-285a-11e8-98ec-2ea481269833.png">

**Comment by dwalintukan** [comment]
#330 fixes the missing name for CREATEEVENT types.

The other ones missing for bet and set result are old bad txs that don't have the topic event so it can look up the name. Meaning, youll have to delete your db to not show bad ones. But all new ones will have the name.
