### ISSUE TITLE
Balance transfer to myself is pending forever

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#331]
<img width="1274" alt="screen shot 2018-03-16 at 2 59 00 pm" src="https://user-images.githubusercontent.com/1126827/37507661-b5585168-292a-11e8-8669-831bf62c57e1.png">

**Comment by dwalintukan** [comment]
@liviavinci I think that is because of a bad UTXO. I get those two on my end due to wallet conflicts.

**Comment by dwalintukan** [comment]
I am closing this for now because I believe it is related to my bad wallet UTXOs. Will reopen later if it pops up again.
