### ISSUE TITLE
Creation of event has been pending forever

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#334]
These two events has been pending forever.

<img width="1281" alt="screen shot 2018-03-19 at 2 26 46 am" src="https://user-images.githubusercontent.com/1126827/37569434-0dc12340-2b1d-11e8-843b-c334a31632fc.png">

**Comment by dwalintukan** [comment]
@liviavinci can you give me the txids for these pending Oracles? use `http://127.0.0.1:5555/graphiql`

**Comment by dwalintukan** [comment]
almost completely sure this is related to my corrupted wallet UTXOs. we will clear our pending txs after a certain amount of time (or blocks). https://github.com/bodhiproject/bodhi-graphql/issues/150
