### ISSUE TITLE
Add txid to all tx history

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#347]
![image](https://user-images.githubusercontent.com/4350404/37694575-00e11dee-2cfb-11e8-8bce-6e6f92c5b450.png)

https://testnet.qtum.org/tx/34ea230c5058ed5d470b7fc21d20832855cb575d059f12af4c8550af0576c215

1. My Activities -> Activity History
2. My Wallet -> Transfer History
3. Oracle Detail page
4. Topic Detail page

**Comment by liviavinci** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/371
