### ISSUE TITLE
Find a better date picker and time picker

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#357]

**Comment by lillland** [comment]
I found these link: 
http://t00rk.github.io/bootstrap-material-datetimepicker/  
you can pick year/month/day/hour/minute

https://mdbootstrap.com/javascript/date-picker/#events 
this one likes better, but no time picker.

**Comment by liviavinci** [comment]
@lillland the first one is great!

**Comment by alex-cory** [comment]
I think [this one](https://material-ui-pickers.firebaseapp.com/demo/datetimepicker) is the exact one we were looking for.
![image](https://user-images.githubusercontent.com/5455859/40740715-6cc4a8f2-63fe-11e8-99e6-54fa78e96465.png)

**Comment by amazingandyyy** [comment]
in order to add this package, new picker, we need to use @material-ui/core(v1.4) package, current we are using material-ui(v0.9)

In order to use @material-ui/core package, we need to update to React 16

**Comment by amazingandyyy** [comment]
@dwalintukan I have successfully updated to React 16 without error, 
1. not sure if this should be seperate PR
2. not sure if no error means "No side effect"

I also update tried to update to @material-ui/core, which updated over 80 files, will the PR be too fat?
I stay the latest code [here on my own branch](https://github.com/amazingandyyy/bodhi-ui/tree/new_date_picker)

Will need to confirm 
1. do we want to update to React 16?
2. do we want to update to @material-ui/core with many refactor of files?
3. should they be seperate PRs? 

Thanks

**Comment by dwalintukan** [comment]
1. Yes we do want to keep updated. How long is ETA for the refactor?
2/3. If the refactor is going to be big, lets create a master sub-branch then do PRs into that master sub.

**Comment by amazingandyyy** [comment]
ETA for @material-ui/core is around one afternoon, refactor + debug of some incompatible component e.g. Button.

**Comment by amazingandyyy** [comment]
will do separate PR for updating React and breaking @material-ui into multiple PRs

**Comment by dwalintukan** [comment]
@amazingandyyy sounds good. the material UI lib might need a lot of updating too?

**Comment by amazingandyyy** [comment]
Yes! And I original planned to refactor the material ui this afternoon, but I decided to move to tmr’s todo list since going through qweb3 and bodhi-server took more time than I expected. 

Will make the refactor PR send tmr!

**Comment by ippudo** [comment]
I think I may take this task

**Comment by dwalintukan** [comment]
@ippudo look into the one that Alex posted above ^. Was looking into one that is familiar to Androids Date and Time picker.

**Comment by ippudo** [comment]
Completed by #817
