### ISSUE TITLE
Users should be able to know how many text they can put in topic tile and result.

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#365]
We need to let users know how many text they can put in topic tile and result.

Also, we need to check whether the text is too long before we post to blockchain. Otherwise, the topic would be invalid anyway.

**Comment by dwalintukan** [comment]
@TT1943 we show a warning if they go over the hex converted limit:
![image](https://user-images.githubusercontent.com/4350404/37762906-3538303c-2df0-11e8-90ac-48e3543f067f.png)

**Comment by frankobe** [comment]
@TT1943 not a bug, move to `enhancement`

**Comment by TT1943** [comment]
I think the Outcome section works fine (But is it too short to allow that small amount of characters?)
![image](https://user-images.githubusercontent.com/711206/37998017-d7aafb3a-31d1-11e8-8411-e340eb8dfa8e.png)

The topic title section DOESN'T work:
![image](https://user-images.githubusercontent.com/711206/37998037-f10dc62a-31d1-11e8-8a95-12d33aaa6a3a.png)

**Comment by dwalintukan** [comment]
@TT1943 
1. for the outcomes, we have no choice since we are limited to bytes32 types which is 64 english characters. chinese may be diff.
2. look at my screenshot above. its 320 bytes worth of characters, so 640 english chars
