### ISSUE TITLE
Remove Invalid from betting result list

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#368]
I think this is a bug. We are not supposed to show `invalid` in betting result list. Please remove it, and forbidden users to bet on invalid during betting state.

We need to show `invalid` in setting/voting result list.
If the final result is `invalid`, 1% of total betting fund (because no one's prediction is correct) is charged for rewarding setter/voter. 99% of total betting fund is returned back to betters.

I am not sure how much work this bug fix will get involved. Let's discuss here.

**Comment by frankobe** [comment]
@TT1943 I dunt think `invalid` is shown in betting result list. Can u double check and close it?
