### ISSUE TITLE
UI shows I have withdrawn even though I haven't

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#375]
My wallet address: `qWfKSEeccMYW7eqUejFDNaUtXhyV5vaHVV`

As  you can see I have reward from this event, and it shows I have withdrawn:
![image](https://user-images.githubusercontent.com/711206/37808388-63d28c32-2e07-11e8-9471-64718fd3813d.png)

But as you can see from the tx history, I haven't withdawn:
![image](https://user-images.githubusercontent.com/711206/37808403-735266c8-2e07-11e8-8c3f-7f0b3ce2c808.png)

**Comment by dwalintukan** [comment]
Fixed in #342

**Comment by frankobe** [comment]
@TT1943 can u verify and close it
