### ISSUE TITLE
Tx went through, but the UI shows pending

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#376]
tx
https://testnet.qtum.org/tx/548638ab969f8beeeab7fcdbd684ec0a0e5d4b7aea88f0fa8f271cfaa391e0a3

Pending 
![image](https://user-images.githubusercontent.com/711206/37809322-f6ae4150-2e0b-11e8-9ba3-776e87fe80fe.png)

**Comment by dwalintukan** [comment]
BE changed needed: https://github.com/bodhiproject/bodhi-graphql/issues/156
