### ISSUE TITLE
After 0%, I see empty %

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#383]
And then 99%, after a while. Not a big bug.
![image](https://user-images.githubusercontent.com/711206/37861569-903cbc8c-2ef9-11e8-834f-a85ffcf9159f.png)

**Comment by frankobe** [comment]
@alex-cory I think this is due to the long response time from `qtumd`, if no result returned after timeout, can we ignore that response and keep the sync percent as the same level

**Comment by dwalintukan** [comment]
Not a FE bug.
fixed: https://github.com/bodhiproject/bodhi-graphql/pull/189

**Comment by liviavinci** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/472
