### ISSUE TITLE
Now I successfully create an event, but the home page still show "pending confirmation"

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#386]
I think refresh is needed.
HMMMM, it seems not about refreshing. I restart the app, it still shows `pending transaction`, but all txs are confirmed.

![image](https://user-images.githubusercontent.com/711206/37861745-71782f94-2efd-11e8-843c-243fa296f504.png)

![image](https://user-images.githubusercontent.com/711206/37861746-760c59c2-2efd-11e8-9ba0-70d558a34489.png)

![image](https://user-images.githubusercontent.com/711206/37861767-b3a33922-2efd-11e8-86b0-075326471a29.png)

**Comment by dwalintukan** [comment]
I believe the pending one might be the one you created before that failed. Will investigate.

**Comment by TT1943** [comment]
HMMMM, it seems not about refreshing. I restart the app, it still shows `pending transaction`, but all txs are confirmed.

**Comment by dwalintukan** [comment]
After the first failed create event, did you see the Pending Event? Or is that one from the second create event.

**Comment by dwalintukan** [comment]
I'm trying to differentiate if that pending one is from the first or second create event

**Comment by dwalintukan** [comment]
cannot repro this. can you try it again?

**Comment by dwalintukan** [comment]
fixed in https://github.com/bodhiproject/bodhi-graphql/pull/160

**Comment by dwalintukan** [comment]
@tt1943 already fixed in graphql bug

**Comment by frankobe** [comment]
@TT1943 can u verify and close it
