### ISSUE TITLE
Event is GONE after I download the latest version (previous was pending forever)

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#393]
1. It shows pending confirmation on `QTUM prediction` after event creation

2. Then it shows the two tx are successful:
![image](https://user-images.githubusercontent.com/711206/37886413-14eee6ea-3070-11e8-9475-ce18c4f2801a.png)

3. Go to `QTUM prediction`, the "New version event creation" is GONE!
![image](https://user-images.githubusercontent.com/711206/37886420-27b94e96-3070-11e8-9e48-33ef910f6b69.png)

**Comment by dwalintukan** [comment]
@TT1943 I see this Oracle in the DB. I think it's in your Result Set tab.

**Comment by frankobe** [comment]
@dwalintukan @TT1943 is this issue still valid or a bug

**Comment by frankobe** [comment]
From #404, the transaction table in `My activities` may not get updated properly. So we cant determine the state from UI
