### ISSUE TITLE
For failed pending confirmation topic, we need to enable users to retry on the failed transaction

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#406]
We need to enable that, otherwise it shows "pending confirmation" forever on users' UI.
If you think think there is no enough time to work on this `retry mechanism`,  at least we need to enable to delete the pending topic, which I think it is not so perfect, but better than showing `pending` forever.

**Comment by frankobe** [comment]
@TT1943 failed transaction will be marked as fail in the transaction table, then the `placeholder` events will be deleted. 

@dwalintukan can we identify whether this is a FE query update issue? BE logic looks correct unless TT quits in the middle of updating failed transaction

For garbage collection deletion, https://github.com/bodhiproject/bodhi-graphql/issues/150

**Comment by dwalintukan** [comment]
This issue that caused a stuck Pending Oracle is fixed. Will change this into a feature. We will need to add logic to do cleanup of stuck pending Oracles.

**Comment by frankobe** [comment]
We rarely capture failure due to network error or payload error, so wont retry for them
