### ISSUE TITLE
Display the amount charged instead of the amount user enter

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#411]
![image](https://user-images.githubusercontent.com/10339131/37944003-d6035758-312e-11e8-952d-431548047980.png)
threshold is 110, the second vote enters 23BOT, but actually only charged 10 BOT, should display 10BOT instead of 23.

**Comment by dwalintukan** [comment]
@henryzbw this is actually going to require some BE changes. going to think about this if its worth it for the mainnet release.

**Comment by dwalintukan** [comment]
Solved by auto adjusting the amount when entering it into the amount field.
