### ISSUE TITLE
Show Result History globally, not just in Withdraw page.

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#421]
We need to let ALL users in ALL stages to see the status of `Result History`, not just in Withdraw page. Note that, the `Result History` should show history from all users, not just your own result history

**Comment by dwalintukan** [comment]
This was done per design specs. We will add the result history to all detail pages. And there's only type of one result history, all users are the same.

**Comment by dwalintukan** [comment]
#430
