### ISSUE TITLE
Uservoice

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#433]

**Comment by amazingandyyy** [comment]
is it still pending? @dwalintukan

**Comment by dwalintukan** [comment]
@amazingandyyy We have no yet created the feature for this yet. It's basically supposed to be a place for user inputted feedback. We can add this in an upcoming sprint.

**Comment by amazingandyyy** [comment]
@dwalintukan ok! I see. I think a good way is to direct users to the slack group as a Q/A public channel.
