### ISSUE TITLE
vote amount display is wrong and qtum showed unexpected

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#441]
![image](https://user-images.githubusercontent.com/10339131/38116291-4d89fcfa-3364-11e8-942b-64f690af0044.png)
![image](https://user-images.githubusercontent.com/10339131/38116321-6680e746-3364-11e8-8ead-1caa1df7b296.png)
Lili vote 20BOT on iPad, but only shows 0.773594BOT,
And Lili doesn't bet qtum, near the withdraw button, it has 69.73703981 QTUM can be withdrawn.
`withdraw`
999482b755955b4a25fc3aecd4d9f9c63231c9c008e7df7341b1be570b9a7aca
`vote on ipad`
a52bb6819c8fdc59c319485b3e27d2fa9d2811444249e083b0f9e54723651deb
`vote on iphone`
e09fdad82f1a6a75de4ecf415bdb3311ae35733da821afc960cd88081f724a0c

And for Ying's
![image](https://user-images.githubusercontent.com/10339131/38116540-656a2182-3365-11e8-97fe-84d25bde0574.png)
![image](https://user-images.githubusercontent.com/10339131/38116936-34ed7890-3367-11e8-9a4a-138ab3014bbc.png)

the withdraw row doesn't look right, maybe because her laptop is small.
She vote 20BOT on iPad, only shows 0.773594BOT
`withdraw`
bdc3a315aa3b2e855cb90d058799b4e4043874d486c9eae25999ddda2e8378c9
`Vote`
ec7265220cd52832a2edc4590ff914800066ed66b4f0033bf1089e31e82c067a

**Comment by dwalintukan** [comment]
#448 fixed
please verify

**Comment by henryzbw** [comment]
@dwalintukan Actually, i don't know how to verify this. Since I cannot reappear this. Does the 0.6.3 contains this fix? I download 0.6.3 on Ying's computer and replace 0.6.2. Open the same one event detail page, the number still the same.

**Comment by henryzbw** [comment]
tried once, happened again on my computer
![image](https://user-images.githubusercontent.com/10339131/38159291-4184f13e-345a-11e8-8454-93a75475007d.png)

**Comment by dwalintukan** [comment]
This is the same issue as the other issue you have open right? #445

**Comment by henryzbw** [comment]
![image](https://user-images.githubusercontent.com/10339131/38159772-53369dc4-3464-11e8-94e2-c5c239239a2b.png)

@dwalintukan  no, look at the red circle, it's not the right number.

**Comment by dwalintukan** [comment]
@henryzbw Ok will fix this also with the return rate percentage.

**Comment by henryzbw** [comment]
@dwalintukan 
test today,
the bot amount showed the same strange number.

![image](https://user-images.githubusercontent.com/10339131/38219621-485d211a-368b-11e8-82ba-731d679c903c.png)
