### ISSUE TITLE
I can't see existed prediction event in BOT court.

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#442]
There are supposed to have many events. For some reason I am not able to see it. Lili mentioned that I have to delete data and resync. Can we automatically fix it?

![image](https://user-images.githubusercontent.com/711206/38118119-7f8af5f2-336d-11e8-8fb6-c43586843a52.png)

**Comment by liviavinci** [comment]
this is because we deployed a new contract right? @dwalintukan

**Comment by dwalintukan** [comment]
@TT1943 @liviavinci Yes, this is a new contract. It will only show the items for this specific contract. For our first version we will confine events to a specific contract version.

version 0.7.0 -> all versions starting with 0 will use the same contract when we deploy on mainnet.
version 1.0.0 -> if we increment the major version number (1) then it will signify a new contract. v0 and v1 will have different events.

It is too messy and can bring a lot of bugs/unexpected consequences if we mix all of them together for now. We need to plan this out carefully and thoughtfully after the mainnet launch for future versions.
