### ISSUE TITLE
cannot see the event in withdraw page

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#444]
I participated in the event in bet,vote phases(i didn't bet or vote on the final result), but when it comes to withdraw pahse, i cannot see it under my withdraw navigation tab, but when i click `view event` from `activities history`, i can go to the withdraw detail page for that event. 
but in my db, this event is existed.
Is this designed to be so?

**Comment by liviavinci** [comment]
@henryzbw currently it is designed to be this way @TT1943 this is the case we were talking about. Only showing withdrawable events under the activities tab might be confusing to some users.

**Comment by dwalintukan** [comment]
@henryzbw it means you did not win anything or arent the creator (escrow depositer) of the event.
