### ISSUE TITLE
return rate formula is wrong

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#445]
Test today, when we vote on different results during `bot court`, the current return rate is calculated by `(your bot winning+escort bot) /bot voted on this result by you`, but it should be `your bot winning/bot voted on all the results by you`,

**Comment by dwalintukan** [comment]
@henryzbw That is incorrect. If you bet/vote on A, B, and C, and only A is the outcome. Why would you get your money back from B and C?

**Comment by dwalintukan** [comment]
#448

**Comment by henryzbw** [comment]
![image](https://user-images.githubusercontent.com/10339131/38159315-9ae41552-345a-11e8-91a8-50ebd4bddecf.png)
![image](https://user-images.githubusercontent.com/10339131/38159321-a5fa5f28-345a-11e8-857a-55ef8459c790.png)
![image](https://user-images.githubusercontent.com/10339131/38159328-d565fa1a-345a-11e8-973f-9e2484e8dd41.png)



BOT return rate looks right now. 
but the QTUM return rate seems wrong.

```
CREATE 

BET #1 10 #2 20
Set #2
VOTE
#0 30
#1 110
#2 20 Ying 101
```

here is the bet vote amount, Ying vote 101 on #2, others are made by me.  i actually get less QTUM than I put in. The return rate cannot be that number, right?

**Comment by henryzbw** [comment]
@dwalintukan yes, but the return rate formula for qtum should be the same as for bot, right? for this event, i actually lose qtum, so it should be a negative number, right?
= (your qtum winning / total qtum you bet)

**Comment by dwalintukan** [comment]
@henryzbw 
QTUM Return Rate:
```
losersTotal = totalLosingQtumBets * 1 / 100
qtumWon = (yourQtumWinningBets / totalQtumWinningBets * losersTotal) + yourQtumWinningBets
```

**Comment by dwalintukan** [comment]
As discussed, the `QTUM Return Rate %` is wrong

**Comment by henryzbw** [comment]
@dwalintukan still exists, just follow
