### ISSUE TITLE
Fix validation on Event Name length

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#449]

**Comment by liviavinci** [comment]
@dwalintukan wanna expand on this?

**Comment by liviavinci** [comment]
Cuz we already have a min&max length validation for event name

**Comment by dwalintukan** [comment]
@liviavinci the validation isn't working for the title.

**Comment by liviavinci** [comment]
<img width="954" alt="screen shot 2018-03-31 at 7 30 01 pm" src="https://user-images.githubusercontent.com/1126827/38162775-058b79d0-351a-11e8-9749-bfe94f14a1e6.png">

**Comment by liviavinci** [comment]
@dwalintukan it's working for me?

**Comment by dwalintukan** [comment]
it's working!
