### ISSUE TITLE
result history table is wrong

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#457]
![image](https://user-images.githubusercontent.com/10339131/38159351-8c91a1bc-345b-11e8-8376-c9d5665b0ebc.png)
The winning outcome for the vote can never always be the same. since each round we just vote against last round's result.

```
CREATE 

BET #2 10 #3 20
Set #3
VOTE
round1
#1 30
#2 110

round 2
#3 Henry 20 Ying 101
```

**Comment by dwalintukan** [comment]
This seems to be BE bug where all the `resultIdx` are the same once the event goes into Withdraw status.

**Comment by dwalintukan** [comment]
fixed https://github.com/bodhiproject/bodhi-graphql/pull/195
