### ISSUE TITLE
reaction incosistent

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#462]
In the second voting round
Ying typed 50 and wanted to type more digits, it will keep 50 and no more digits added.
but if typed 60 and continued to type more digits, it will have digits added.
Maybe not a bug,
![image](https://user-images.githubusercontent.com/10339131/38210909-a743cd78-366d-11e8-8f50-c64b14dc306b.png)
![image](https://user-images.githubusercontent.com/10339131/38210916-ac0971dc-366d-11e8-9dfa-e0959483e3a5.png)

**Comment by dwalintukan** [comment]
fixed #465
