### ISSUE TITLE
Result history doesn't show wining outcome for betting round

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#463]
After setting result (currently in voting round 1), the result history doesn't show winning outcome for betting round
![image](https://user-images.githubusercontent.com/10339131/38217869-b0f8f156-3684-11e8-9091-4067ea1d0e9f.png)
In voting round 2, the result history doesn't show winning outcome for voting round 1,
![image](https://user-images.githubusercontent.com/10339131/38218972-865062f0-3688-11e8-86fe-a7edd2188729.png)
in voting round 3, the result history doesn't show winning outcome for voting round 2,
![image](https://user-images.githubusercontent.com/10339131/38219266-a73d11ba-3689-11e8-83c7-a36640786321.png)

**Comment by dwalintukan** [comment]
fixed #465
