### ISSUE TITLE
Can bet on ended event?

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#466]

**Comment by liviavinci** [comment]
<img width="1434" alt="screen shot 2018-04-03 at 8 10 51 pm" src="https://user-images.githubusercontent.com/1126827/38248509-2c499a6c-377b-11e8-8212-f0ae4451608a.png">

**Comment by dwalintukan** [comment]
@liviavinci looks like your latest block was behind the ending time. 20:05:36.
The ending countdown time should really be using the latest block time, not current actual time.

**Comment by alex-cory** [comment]
I also noticed if I’m after the betting start time, I cannot bet on an event because `The betting time has not started yet` even though it has started. I’m sure this is related/similar to this issue. Once I get a screenshot, I'll post

**Comment by alex-cory** [comment]
This is still in `Bet` phase even though the end time for betting has passed. 
![image](https://user-images.githubusercontent.com/5455859/38340073-5fe05338-3826-11e8-94fb-a3354f9f300e.png)
