### ISSUE TITLE
Didn't vote but withdraw page shows that i did and has return. Probably confused the set result cost with vote?

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#469]
<img width="846" alt="screen shot 2018-04-04 at 8 04 08 am" src="https://user-images.githubusercontent.com/1126827/38281805-27d7ac1c-37df-11e8-98a7-32b0f63038c8.png">
<img width="846" alt="screen shot 2018-04-04 at 8 04 16 am" src="https://user-images.githubusercontent.com/1126827/38281809-2baed31a-37df-11e8-8c30-0a761deac51a.png">
<img width="837" alt="screen shot 2018-04-04 at 8 04 26 am" src="https://user-images.githubusercontent.com/1126827/38281811-2d8637aa-37df-11e8-9bf8-6ef244e3636e.png">

**Comment by dwalintukan** [comment]
@liviavinci Set Result is treated as a vote. This is how we designed it since it's being used in all areas where votes are concerned.

**Comment by liviavinci** [comment]
@dwalintukan this is a bit weird from the UX perspective. But not launching blocking. Putting it back to backlog

**Comment by frankobe** [comment]
@liviavinci can u suggest a way mking this clearer?

**Comment by dwalintukan** [comment]
Solved with the tooltip for the calculations
