### ISSUE TITLE
Might be an old db thing: bet amount is different between tx history and winning return

### ISSUE THREAD

**Issue by liviavinci** [bodhiproject/bodhi-ui#473]

**Comment by liviavinci** [comment]
<img width="456" alt="screen shot 2018-04-04 at 9 32 52 am" src="https://user-images.githubusercontent.com/1126827/38284323-3744b402-37ed-11e8-9d0e-7ec98ee1f00d.png">
<img width="784" alt="screen shot 2018-04-04 at 9 32 58 am" src="https://user-images.githubusercontent.com/1126827/38284324-377f8a8c-37ed-11e8-925a-a86fe5aa725d.png">
<img width="785" alt="screen shot 2018-04-04 at 9 32 44 am" src="https://user-images.githubusercontent.com/1126827/38284325-37ba1a3a-37ed-11e8-9fc7-6ad021f90ede.png">

**Comment by dwalintukan** [comment]
@liviavinci pull the lastest masters for graph and ui. should be fixed. there was a parsing issue.
