### ISSUE TITLE
Vote for invalid

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#476]
![image](https://user-images.githubusercontent.com/10339131/38332634-5090df62-380b-11e8-82b9-7a5436f7436c.png)

```
CREATE

BET #2 10 YING #3 20
SET #3 100
vote #1 110
```
got 3 same withdraw, and the total vote amount `630` above exceeds total amount 
Also, shouldn't invalid return all the bet and vote amount back to the person who participate?
And the remaining 29.1 qtum is gone, no one can withdraw.

**Comment by dwalintukan** [comment]
@henryzbw already got this fixed in a PR. #475

**Comment by dwalintukan** [comment]
As discussed, the Invalid outcome does not fully refund users yet. This will come in a later version.
