### ISSUE TITLE
when on Oracle page after creating event and waiting on next block, page goes blank

### ISSUE THREAD

**Issue by alex-cory** [bodhiproject/bodhi-ui#479]
I think this happens when the next block comes in because the `topicAddress` and the `address` in the url are `null` and we use those in the constructor to get the `oracle` and set it to state. Since their's no oracle, nothing get's rendered. See these lines

![image](https://user-images.githubusercontent.com/5455859/38340752-dec9c208-3829-11e8-96c4-018463efa1d9.png)

Here's the url while waiting on the event to confirm on the blockchain.
`http://localhost:3000/oracle/null/null/c5a2caed2c06b4eb3b839d2e9bbaf749ec37f51065ee1e5c18ab5f4c7f0781fb`

Maybe we need to force a refresh when these values come in or better yet, don't put them in the url then we don't have to force a refresh.

![image](https://user-images.githubusercontent.com/5455859/38340684-7ac10b5e-3829-11e8-908e-0eea17c4ebee.png)

**Comment by dwalintukan** [comment]
This sounds like a different bug. That looks like a pending Event and should be able to be seen.
