### ISSUE TITLE
Determine if user can setResult or vote rules

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#48]
UI needs to show different views for some different rules:
CentralizedOracle
1. if user is the resultSetter and below the resultSettingEndBlock, then user should see Set Result button. 
2. if current block is above resultSettingEndBlock, any user should see Set Result button.
3. Set Result should alert the user that it will use higher than normal gas costs.

DecentralizedOracle
1. if user's bet will put the result over the consensus threshold, we should let the user know that their vote will require a higher gas cost for their vote (because its creating a new Decentralized contract)
2. if current block is past arbitrationEndBlock, the Finalize button should only be shown

**Comment by chrisli30** [comment]
Set Result should also alert the user that it will cost them 100 BOT, right?

**Comment by chrisli30** [comment]
CentralizedOracle No.1 Set Result is done
DecentralizedOracle No. 2 Finalize button is done.

**Comment by chrisli30** [comment]
Centralized 3. and Decentralized 1. are needed for beta. C2. will be addressed later.

**Comment by chrisli30** [comment]
Note to C No.1 if user is the resultSetter and below the resultSettingEndBlock, then user should see Set Result button. For anybody else, hide oracles in Invalid status.
