### ISSUE TITLE
Showing "no enough BOT" while trying to set result

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#480]
When I open the topic detail, I saw this:
![image](https://user-images.githubusercontent.com/711206/38345512-674a6af0-3844-11e8-8d5a-aa3c68ed2647.png)

I think users feel confused about this before they actually see which wallet address is referred.
Only when I click on one option, now I know why.
![image](https://user-images.githubusercontent.com/711206/38345540-94057634-3844-11e8-9722-2f043a007cf8.png)

**Comment by dwalintukan** [comment]
#847 should solve this problem

**Comment by ippudo** [comment]
Feel like it's a different issue

**Comment by dwalintukan** [comment]
@ippudo This is an issue with the currently selected address/wallet. Look at the image. That address only has 72 BOT, not enough for the threshold. This is not a bug.
