### ISSUE TITLE
Syncing on mainnet, progress bar progresses, but the percentage shows 0%

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#490]
![image](https://user-images.githubusercontent.com/711206/38538525-20af936e-3c49-11e8-98db-e898d743d0c5.png)

**Comment by frankobe** [comment]
@TT1943 it is a UI bug, is fixed in #485

**Comment by dwalintukan** [comment]
@xiahong which version are you using?
@frankhu did this make it into 0.7.0?
