### ISSUE TITLE
[Testnet] Why the "My Activities" Count, "Result Setting" Count, "Withdraw" Count are not showing?

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#491]
[Testnet] Why the "My Activities" Count, "Result Setting" Count, "Withdraw" Count are not showing?
![image](https://user-images.githubusercontent.com/711206/38538637-8db262b6-3c49-11e8-8165-34df31e62b68.png)

**Comment by TT1943** [comment]
After I restart the app, it shows again. Potential bug?
![image](https://user-images.githubusercontent.com/711206/38538701-d3115d1c-3c49-11e8-9c11-bd92fd624170.png)

**Comment by dwalintukan** [comment]
suspect API was not fully running before calling to get the actionable items number. should be fixed from: https://github.com/bodhiproject/bodhi-graphql/pull/234/files
