### ISSUE TITLE
[Mainnet] Cannot restart Bodhi on Mainnet after first launch. Not happen on Testnet, why?

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#492]
It looks like the qtumd is still live after I shut down Bodhi on mainnet.
Why it works all fine for testnet? Any difference between mainnet and testnet?
![image](https://user-images.githubusercontent.com/711206/38538749-06b3439c-3c4a-11e8-9e38-a990913c747d.png)

**Comment by frankobe** [comment]
@TT1943 checking

**Comment by dwalintukan** [comment]
@TT1943 looks like you just restarted it too fast. qtumd takes 2-4 secs to shutdown properly.
