### ISSUE TITLE
Add a status bar to display network status: Online/Offline

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-ui#5]
Maybe some overlay at bottom right of page. Need design.

**Comment by chrisli30** [comment]
Won't fix for now. Will resurrect in future.

**Comment by dwalintukan** [comment]
FYI, changed this from showing whether syncing or not to offline/online because technically if you are online, you are always syncing haha.

**Comment by liviavinci** [comment]
Yea I figured lol
