### ISSUE TITLE
Do we need to show BOT balance on setResult and Vote page?

### ISSUE THREAD

**Issue by chrisli30** [bodhiproject/bodhi-ui#50]
Because BOT allowance is critical to make those two calls, we need to show remaining BOT balance on those two pages, or even on topbal for a global group. What do you guys think?

**Comment by dwalintukan** [comment]
I think BOT balance should shown at the top bar along with qtum balance. Users should know how much is in their wallet at any given time.

**Comment by frankobe** [comment]
BOT balance should be in the same level as QTUM balance

**Comment by chrisli30** [comment]
Retrieve BOT balance with polling of getblockcount.

**Comment by chrisli30** [comment]
#52
