### ISSUE TITLE
Back button fix

### ISSUE THREAD

**Issue by alex-cory** [bodhiproject/bodhi-ui#503]
when you click on the transaction from `/activities/history`, it will take you to `/topic/:topicAddress`, and right now we have mappings to where each page is supposed to go back to. Right now, the “back page” for `/topic/:topicAddress` is `/activities/withdraw` but it should go back to `/activities/history`

what we need to do is keep track of the router locations in an array in the redux store, then access the previous location whenever the back button is clicked

**Comment by dwalintukan** [comment]
duplicate #779
