### ISSUE TITLE
Double confirmation for all transactions

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/bodhi-ui#516]
For all gas related issue, show double confirm dialogue before firing requests.

Open another dialog before firing the transaction and let the user know what they are spending.
ie. when placing a bet, show dialog saying: `You are about to place a bet on  'Outcome: A' for 10 QTUM`. or something like that.

**Comment by liviavinci** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/527
