### ISSUE TITLE
create event modal padding

### ISSUE THREAD

**Issue by alex-cory** [bodhiproject/bodhi-ui#522]
2 places
￼
![image](https://user-images.githubusercontent.com/5455859/39368175-bf1dd8a6-49ed-11e8-92d8-b51ebdc661cf.png)
inbetween date time input and block

![image](https://user-images.githubusercontent.com/5455859/39368186-c8a04ecc-49ed-11e8-8c94-2a50b25402d7.png)
around publish button

**Comment by dwalintukan** [comment]
#524
