### ISSUE TITLE
stop dropdown on activities history event name click (non create event)

### ISSUE THREAD

**Issue by alex-cory** [bodhiproject/bodhi-ui#523]
basically, when you click the name of an event, it will open the accordion, and then navigate you to the other page. Should just navigate you without changing the accordion.
![image](https://user-images.githubusercontent.com/5455859/39368569-c5e12fc0-49ee-11e8-9f83-138415064095.png)

**Comment by ippudo** [comment]
@alex-cory Hand me this bug to fix since I just did MobX refactor for this part
