### ISSUE TITLE
label upcoming events in Bodhi Court

### ISSUE THREAD

**Issue by lillland** [bodhiproject/bodhi-ui#542]
Problem: Between the end of betting and beginning of voting, events will disappear for result setting.  Only result setter can see those events.

Solution:  add one sorting" upcoming" in bodhi court, and add a label "upcoming" on the mini card. The CTA area shows text in grey "waiting for result setting" indicates user what's the status of this 
event.  
- [x]  "upcoming" label

- [ ] add "upcoming" in sorting

Mockup:
![home_court_upcoming](https://user-images.githubusercontent.com/5739162/39729235-abefce86-520f-11e8-871c-c5886982a613.png)

Specs:
<img width="855" alt="screen shot 2018-05-07 at 4 00 58 pm" src="https://user-images.githubusercontent.com/5739162/39729265-dbed5a18-520f-11e8-9a1d-c2f0eedbe513.png">

**Comment by dwalintukan** [comment]
@henryzbw we need to show events in BOT Court that are in either Result Setting phase. This is to show the upcoming Oracles that will be appearing in the tab once the result is set.
