### ISSUE TITLE
Pagination doesn't work in Result Setting dashboard

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#553]
Lili found a bug where the Result Setting tab shows 27 items, but only showed 8 and couldn't scroll down.

**Comment by henryzbw** [comment]
@dwalintukan this one is already solved by your pr for withdraw tab?

**Comment by dwalintukan** [comment]
@henryzbw I am not sure I will have to check. Does it happen on your end?
