### ISSUE TITLE
make PR more strict and safe.

### ISSUE THREAD

**Issue by amazingandyyy** [bodhiproject/bodhi-ui#621]
suggest to 
- require every PR review and proved by at least one reviewer before getting merged, current setup is allowing everyone to merge and even the PR requester can merge on his own. -> need TT update setting of the org.
- require `travis` to run style checking for every PR

**Comment by dwalintukan** [comment]
@amazingandyyy sounds good. Will have @TT1943 give me rights to do this.

**Comment by amazingandyyy** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/629 fixed
