### ISSUE TITLE
duplicated waring messages

### ISSUE THREAD

**Issue by amazingandyyy** [bodhiproject/bodhi-ui#622]
As the image shows
https://i.imgur.com/lMnT1bI.png

there are duplicated warning messages of `You don't have enough QTUM`

**Comment by dwalintukan** [comment]
One seems to be for QTUM and the other BOT. Not enough QTUM would be for the tx fee and BOT would be for the escrow.

Oh also btw, you know you can copy/paste images in here? (so you dont have to keep uploading to imgur)

**Comment by amazingandyyy** [comment]
oh! I see!

good to know! cool 

![download](https://user-images.githubusercontent.com/7886068/41482795-9660e77c-708b-11e8-9cee-cfa9958eb969.jpg)
