### ISSUE TITLE
redesign the float menu on mobile phone

### ISSUE THREAD

**Issue by langningsuxuan** [bodhiproject/bodhi-ui#641]
Cause the button couldn't adapt the screen of mobile phone. It's responsive problem. So I redesign the  float menu on mobile phone. It seems reduce the space of the right menu.

**Comment by langningsuxuan** [comment]
https://drive.google.com/drive/folders/1NANVQOTd_pfke-J7iiAAL3fnh_dRdwgW
http://www.iconfont.cn/manage/index?manage_type=myprojects&projectId=580156

**Comment by dwalintukan** [comment]
already created in website repo: https://github.com/bodhiproject/website/issues/276
