### ISSUE TITLE
Voted result does not show correct balance

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#69]
Just voted on a DecentralizedOracle that only has 1 result and its not showing the balance in the Oracle detail page. 

Verified that the vote is showing up in DB:
![image](https://user-images.githubusercontent.com/4350404/34361899-2a6f69aa-eaa1-11e7-8607-fa786ab62348.png)

Here it is showing on the UI. It is getting the real total vote balance, but I think the indexing is off.
![image](https://user-images.githubusercontent.com/4350404/34361907-3b110a84-eaa1-11e7-952a-8638766419ab.png)

**Comment by chrisli30** [comment]
11813666621d1164420a810aa33c6ef933ba309b

**Comment by chrisli30** [comment]
Made it to fixed two digits decimal, e.g. 0.00 or 15.00
