### ISSUE TITLE
MobX: Components/SelectAddressDialog

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#690]

**Comment by ippudo** [comment]
Um I'm not sure but it seems like nothing to do with this component too. Do you have any suggestion about this component?

**Comment by ippudo** [comment]
TODO: dialogVisible

**Comment by dwalintukan** [comment]
@ippudo you should create a store for this component and it will have the `isVisible` in the store to control if it's showing or not. You will then observe this var in the component.

**Comment by ippudo** [comment]
Complete at #763
