### ISSUE TITLE
Allow entering more than allowed in arbitration detail page

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#720]
This is for the Oracle detail page for an arbitration phase. For example:
- Consensus threshold is 110 BOT
- Outcome A already has 109.99999999 BOT voted on it
- If someone wants to vote Outcome A to the threshold, they have to type 0.00000001 in the amount

We will change it so the user can type in whatever they want (eg. 10 BOT), but we will have a message saying something like: `The Consensus Threshold is 110 BOT and Outcome A already has 109.99999999 BOT. You can only vote up to the Consensus Threshold. Only 0.00000001 BOT will be charged.`

**Comment by alex-cory** [comment]
https://github.com/bodhiproject/bodhi-ui/pull/730

**Comment by amazingandyyy** [comment]
This is not related to 730, mistakes.

**Comment by ippudo** [comment]
Since vote amount will be fixed automatically to the threshold, do we still need to do this task?
