### ISSUE TITLE
change date format strings for different locales

### ISSUE THREAD

**Issue by alex-cory** [bodhiproject/bodhi-ui#762]
https://momentjs.com/docs/#/customization/long-date-formats/
right now we're using custom helper methods like `formatShortLocalDateTimeString`. We shouldn't be doing it this way. We should be doing `moment(dateTime).format('L')` or something along those lines

**Comment by ippudo** [comment]
Note: moment.js locale seems not be set at the initialization of UIstore.

**Comment by ippudo** [comment]
It seems like momentjs doesn't support custom format such like 
moment().format('formatShortLocalDateTimeString')
