### ISSUE TITLE
Can not vote decimal number but Consensus Threshold can become decimal. [VOTE]

### ISSUE THREAD

**Issue by amazingandyyy** [bodhiproject/bodhi-ui#787]
Vote(Arbitrate) in decimal number will throw 500 error

**Comment by amazingandyyy** [comment]
need to fix it in server

**Comment by ippudo** [comment]
It may become an important bug since currently the Consensus Threshold can become decimal (e.g. 133.1 BOT), which will cause a fault vote event that no one can vote.

**Comment by amazingandyyy** [comment]
@dwalintukan  need to fix it in GraphQL Scheme (server)

**Comment by ippudo** [comment]
Fixed in #825 I believe

**Comment by dwalintukan** [comment]
Fixed in 825
