### ISSUE TITLE
Checking QTUM amount of wrong total in [CreateEvent]

### ISSUE THREAD

**Issue by amazingandyyy** [bodhiproject/bodhi-ui#789]
Checking QTUM amount of wrong total in [CreateEvent]
And also need to check BOT amount

**Comment by amazingandyyy** [comment]
related to #656

**Comment by ippudo** [comment]
BOT amount is validated by another standalone function.
But I'm feeling the total amount and display are wrong.
Need further check.

**Comment by ippudo** [comment]
Part done, other go #894
