### ISSUE TITLE
Sometimes qtum amount is inconsistent in app wallet with qtum explorer.

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#797]
![image](https://user-images.githubusercontent.com/10339131/43108292-d59d0ee8-8e95-11e8-82c0-1bf8393249df.png)
![image](https://user-images.githubusercontent.com/10339131/43108310-e6a8f742-8e95-11e8-8956-aa06881e99ea.png)

**Comment by dwalintukan** [comment]
QTUM wallet problem
