### ISSUE TITLE
Move `localizeInvalidOption` logic when parsing the the object

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#804]
Currently we have a helper method to localize the text of the `Invalid` option. Instead of having to call this helper method when its needed, let's change the text in the actual `Event` instance `Invalid` option when the object is parsed.

**Comment by BernardHan** [comment]
This issue was already fixed.
1. localizeInvalidOption helper function only exists in scenes/Event/scenes/topic.js, which is not imported anywhere
2. scenes/Event/scenes/Oracle/components/Option/index.js line 53 shows this issue is already handled

**Comment by dwalintukan** [comment]
@BernardHan Look at `src/scenes/Event/components/EventTxHistory/resultHistory.js L80`.

What I meant for this PR was to change this at the Model layer so this change would be done at `src/stores/models/Topic.js` & `src/stores/models/Oracle.js`. The purpose of this is so we parse it once and anytime we want to get the localized name after that we dont have to do the localization on the spot.

**Comment by ippudo** [comment]
I'm curious about this task. I'm feeling like we can not put it at model layer to expect be calculate only once. When UI language changes, localized invalid string need to be also updated.
