### ISSUE TITLE
Implement Empty Page Placeholder

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#824]
We need to have some sort of placeholder graphic for dashboards that are empty.
@lillland can we get a design on this?

![image](https://user-images.githubusercontent.com/4350404/44078984-18fc8c98-9fd2-11e8-89bc-a9235475ebc3.png)

**Comment by lillland** [comment]
https://www.figma.com/file/ChDp3DmTpPvcA8nrvpc6dgFK/Bodhi-App-UI?node-id=22%3A14

<img width="823" alt="screen shot 2018-09-18 at 1 59 35 pm" src="https://user-images.githubusercontent.com/5739162/45716251-391ddd80-bb4b-11e8-9e1d-7b127f81bdc7.png">

**Comment by dwalintukan** [comment]
@lillland looks great! can we get one for the `My Activites` tabs as well?
