### ISSUE TITLE
Event detail page does not refresh after transaction is confirmed

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#831]

**Comment by BernardHan** [comment]
@dwalintukan 
I've been studying this issue and learned a lot related to our backend, I was told by others that this refresh feature used to be implemented in `redux`. So I decided to build it as a new feature.

I was trying to have an `observable` in `Model/Oracle.js` to record how many transactions get confirmed, when it changes, the `Options` component in the page gets rerendered. However, I cannot find anywhere that transaction status gets changed, so I guess this is in the backend and get queried into frontend.

I will look for another way and manage to finish it by tomorrow, but please shed light on me if you have any (which is highly possible).

**Comment by dwalintukan** [comment]
@BernardHan look at `EventStore L44`. that is the txs array that gets updated. txs get manually inserted into the array like `L589`. lets keep the observable in the `EventStore`

**Comment by BernardHan** [comment]
@dwalintukan 
`this.transactions.unshift(new Transaction(newTx));`
The newTx here is the pending transaction I think?
But where does the status get changed?

**Comment by dwalintukan** [comment]
@bernardhan the status should be getting changed when a new block comes and a new `queryAllTransactions()` gets executed. When that query comes back, it's replacing the entire list, not just the pending one.
