### ISSUE TITLE
Smaller font for Result Setter field

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#834]
@lillland what do you think of smaller font for the `result setter` field? looks ugly IMO to have the address split up in multiple lines.

![image](https://user-images.githubusercontent.com/4350404/44092518-de8833ea-9ffa-11e8-9799-66b6687a6d11.png)

**Comment by lillland** [comment]
what's the current font-size?

**Comment by dwalintukan** [comment]
looks like we are using 24px
