### ISSUE TITLE
Result History showing current round

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#835]
This event is in Arbitration Round 1. It should not be showing the current round in the `Result History`. Believe this is a bug.

![image](https://user-images.githubusercontent.com/4350404/44092609-1d4e07c6-9ffb-11e8-9d76-1921e2d8a8e3.png)

**Comment by ippudo** [comment]
Is this really consider to a bug? I think the whole logic at result history is weird and need to be discussed
