### ISSUE TITLE
Validation for Create Event times does not work

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#838]
Betting start and end times should at least be 30 minutes apart.
Result setting start and end times should be at least 30 mins apart.

![image](https://user-images.githubusercontent.com/4350404/44096795-4dec9ad6-a006-11e8-8655-331fe654223e.png)

**Comment by ippudo** [comment]
In dev mode the limit is currently set to 2 mins. 
It's hardcoded in create event store and can be adjusted.

**Comment by ippudo** [comment]
Not a bug
