### ISSUE TITLE
Withdraw Transactions showing null for the result name

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#842]
Withdraw Detail page.

![image](https://user-images.githubusercontent.com/4350404/44097818-e0905ba0-a008-11e8-80f3-ab4cee3c5179.png)

**Comment by BernardHan** [comment]
![image](https://user-images.githubusercontent.com/23019256/44176110-5cadbe00-a09d-11e8-9114-f2a0ae726043.png)

@dwalintukan I have fixed the null string, but when I try to show the amount, I notice that the `WITHDRAW` and `WITHDRAW ESCROW` transactions have `null` `amount` and `token`.

I believe these transactions come from Event/store.js `queryAllTransactions`?
