### ISSUE TITLE
Move EventWarning above the CTA button and grey CTA button if disabled in Event detail

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#847]
- [ ] Move the event warning (light blue box with text) right above the CTA button
- [x] Grey out the CTA button if it is disabled

![image](https://user-images.githubusercontent.com/4350404/44139580-a7de5ef8-a0a1-11e8-84f1-44baa5edfae5.png)

**Comment by dwalintukan** [comment]
Ok, we can discuss this at the next meeting.

**Comment by ippudo** [comment]
Move the event warning from the light blue box and fill them into error for each fields.

**Comment by dwalintukan** [comment]
@ippudo Actually, its:
1. Keep any of the `EventWarningType.INFO or HIGHLIGHT` in the same spot
2. Add warning text under the `Amount` and `Address` fields. Don't use the same EventWarning component. Just some small text will do, ask Lili. Pretty sure she will follow the same design as Qrypto.
