### ISSUE TITLE
Several WithdrawDialog Bugs

### ISSUE THREAD

**Issue by ippudo** [bodhiproject/bodhi-ui#855]
Fields at store didn't get cleared when the dialog open.

Can send BOT to any target wallet address.

Some fields not initialized at store.

BOT amount incorrect at confirmtxdialog

**Comment by dwalintukan** [comment]
Can send BOT to any target wallet address. - check the `validateAddress` api call. it should be working.

BOT amount incorrect at confirmtxdialog - prob need to use the `satoshiToDecimal` conversion in the dialog.
