### ISSUE TITLE
Cannot do any Tx

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#864]
@dwalintukan this is very critical. After your commit 99b525a2d36b874b03594697845a14c091b3a5b4 . All Tx cannot be done. 
![image](https://user-images.githubusercontent.com/10339131/44283545-96a0d080-a213-11e8-8a63-8cbc7471f96c.png)
don't find the reason yet. But we cannot cut a release if this bug is still exist.

**Comment by ippudo** [comment]
#865
