### ISSUE TITLE
Appolo error at console while block number updated

### ISSUE THREAD

**Issue by ippudo** [bodhiproject/bodhi-ui#866]
![appolo](https://user-images.githubusercontent.com/9134404/44287799-f488e480-a222-11e8-8ca2-90735a92ec90.png)

This bugs doesn't related to removing redux.

**Comment by ippudo** [comment]
.\src\scenes\Event\store.js L190

`    // Fetch transactions during new block
    reaction(
      () => this.app.global.syncBlockNum,
      () => this.queryTransactions(),
    );`

This should be the problem. Feel like we need to remove this, but I'm not sure whether it's safe.

**Comment by amazingandyyy** [comment]
@dwalintukan
