### ISSUE TITLE
Outdated maxTransactionFee

### ISSUE THREAD

**Issue by ippudo** [bodhiproject/bodhi-ui#892]
We're now setting maxTransactionFee to 0.1 for validation use, but the transaction fee can easily beyond this amount ( around 0.27 in my Computer ).

![create4](https://user-images.githubusercontent.com/9134404/44437963-c6343d80-a571-11e8-9b81-56eac814edd8.png)
Then we'll see a lot of this by doing BET/CREATE/TRANSFER when we're low in qtum

**Comment by dwalintukan** [comment]
@ippudo Lets remove this static `0.1 maxTransactionFee`. We can replace it with the actual max fee with the `/transaction-cost` api.
