### ISSUE TITLE
Wrong BOT amount shown at Create Event confirm dialog

### ISSUE THREAD

**Issue by ippudo** [bodhiproject/bodhi-ui#894]
![create1](https://user-images.githubusercontent.com/9134404/44437990-f1b72800-a571-11e8-8b37-80669b6fe9c9.png)

The data from the post API returns array of 2 and each has a BOT amount.

**Comment by ippudo** [comment]
By the way if you has already got an successful "Approve" transaction but "create event" transaction is still pending, then you will get a different txfees data from the API.
![create2](https://user-images.githubusercontent.com/9134404/44438049-393db400-a572-11e8-9368-a32535985ce6.png)
Though it has no meaning since you can't create any new event at that period, and will get this:
![create3](https://user-images.githubusercontent.com/9134404/44438115-8c176b80-a572-11e8-96dd-98cdde377aef.png)

**Comment by dwalintukan** [comment]
Ya that logic with the `Approve` is expected. We should better inform the user that they cant create another Event until the other one is finished.

1. Disable Create button
2. Add an EventWarning that there is a pending Create Event tx
