### ISSUE TITLE
Syncing page doesn't get updated automatically at LightClient

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#898]
![image](https://user-images.githubusercontent.com/10339131/44490886-78244600-a614-11e8-980c-707c6b9fa7cd.png)

![image](https://user-images.githubusercontent.com/10339131/44491069-f08b0700-a614-11e8-92d4-5386266543ce.png)

Need to refresh to see the syncing number change when using `light-client-feature server branch`

Not sure if its front -end bug or backend

**Comment by dwalintukan** [comment]
should be fixed in the latest light-client branch. had to fix the SSL on it.
