### ISSUE TITLE
UI not responsive

### ISSUE THREAD

**Issue by BernardHan** [bodhiproject/bodhi-ui#901]
![image](https://user-images.githubusercontent.com/23019256/44492829-b02e8780-a61a-11e8-890e-78b16f636bfe.png)

**Comment by BernardHan** [comment]
NOTE:
- Vertical scrollable
- Wallet tutorial content rewrite
- Accept button until Agreement scroll to the end

**Comment by dwalintukan** [comment]
This is being handled by the outsourced team.
