### ISSUE TITLE
new Date Picker or CreateEvent save the time in a Wrong format

### ISSUE THREAD

**Issue by amazingandyyy** [bodhiproject/bodhi-ui#907]
The standard format of time should be "1535760780" ten degits long, but now I only see 7 digits, this causing our event listing sorting errors.

@ippudo

**Comment by amazingandyyy** [comment]
![screen shot 2018-08-23 at 16 58 59](https://user-images.githubusercontent.com/7886068/44557906-ee4ca980-a6f5-11e8-874a-0fcf4985c51a.png)

**Comment by ippudo** [comment]
@dwalintukan Do we have method to cleanup these wrongly created events? This is not a bug related to the current version. It's just because there are some event accidentally created during mobx refactoring with wrong date format.

**Comment by dwalintukan** [comment]
@ippudo Not possible. Once its on the blockchain it's there for good which is why we need to be super careful to not submit bad data to the blockchain on the UI side. It's ok, we will just leave them there. It is testnet only.
