### ISSUE TITLE
BOT court in Chinese is “BOT法庭” it's difficult to understand for users.

### ISSUE THREAD

**Issue by JackLamCHN** [bodhiproject/bodhi-ui#920]
BOT court in Chinese is “BOT法庭” it's difficult for users who use Bodhi first time to understand.

**Comment by dwalintukan** [comment]
@JackLamCHN do you have a translation for it? should we use `BOT法庭`?

**Comment by JackLamCHN** [comment]
@dwalintukan Hi Deric，I think “BOT仲裁”is the most suitable translate for it.
