### ISSUE TITLE
Show the full history of the Event on both oracle and topic

### ISSUE THREAD

**Issue by ippudo** [bodhiproject/bodhi-ui#943]
From Weekly Sync

**Comment by dwalintukan** [comment]
Not exactly combine the two pages, but more like show the full history of the Event on both. Let's leave the Oracle and Topic pages separate. The main thing that will change is that we fetch ALL the transactions for this Event from all the Oracles/Topics which means we query the tx table by `topicAddress`.

**Comment by TT1943** [comment]
close due to new ui change
