### ISSUE TITLE
Pull transaction list based on Votes, Set Results, Finalizes, Withdraws

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#967]
Currently the `Transactions` table in the Event Detail is pulling off the `Transactions DB`. This is not good since it is not based off the blockchain data. Transactions is a model we created ourselves.

We should be pulling off the `Votes, Set Results, Finalizes, Withdraws` tables instead. These are all confirmed by the blockchain.

Will require some changes to the backend.

**Comment by BernardHan** [comment]
This issue can get started after server issue 144 finished.
https://github.com/bodhiproject/bodhi-server/issues/144
