### ISSUE TITLE
crash when create event failed

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#978]
repro:
1. create event
2. click into the unconfirmed one
3. when new block comes, the transaction failed, it will crash.

![image](https://user-images.githubusercontent.com/10339131/46036952-ae456180-c0bb-11e8-961a-2a7760443550.png)

**Comment by dwalintukan** [comment]
@henryzbw do you have more info? topicAddress, oracleAddress, hashId?

**Comment by henryzbw** [comment]
this happens when `approvecreateevent` fails, its on my local,

**Comment by dwalintukan** [comment]
@henryzbw are you unable to create events at all then?
