### ISSUE TITLE
[Design] Need design for showing last results in all Decentralized Oracles

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#98]
<img width="1127" alt="screen shot 2018-01-23 at 10 11 28 am" src="https://user-images.githubusercontent.com/4350404/35257779-e6c897f6-002d-11e8-8276-96fe6567f77c.png">

We would like to show the results of all the `DecentralizedOracles`. Need a design on this.

**Comment by lillland** [comment]
we had design on this. 
<img width="1373" alt="screen shot 2018-01-24 at 5 00 40 pm" src="https://user-images.githubusercontent.com/5739162/35365248-55d1c988-0128-11e8-8f49-1059bc8d493d.png">

**Comment by dwalintukan** [comment]
Ah I see. Sorry forgot about it, was thinking our current app fully matches the design. Thanks @lillland
