### ISSUE TITLE
ACCOUNT_CHANGED -> QRYPTO_ACCOUNT_CHANGED

### ISSUE THREAD

**Issue by soshochang** [bodhiproject/bodhi-ui#994]
With the latest merged pr of qrypto (173)
https://github.com/bodhiproject/qrypto/pull/173
Bodhi-ui now needs to listen for QRYPTO_ACCOUNT_CHANGED  rather than ACCOUNT_CHANGED
(Note that this pr is as 9/28 3PM PST merged into master, but not yet published(I didn't want it impinging on any other testing))

**Comment by dwalintukan** [comment]
#997 done, thanks for reminding
