### ISSUE TITLE
Confirm tx data not being passed to qrypto

### ISSUE THREAD

**Issue by soshochang** [bodhiproject/bodhi-ui#995]
Notice that the confirm tx qrypto popup has no populated data, the cancel and confirm buttons also do not work

![screen shot 2018-09-28 at 3 12 57 pm](https://user-images.githubusercontent.com/4063649/46235980-9ecf4e00-c331-11e8-8ddd-d7ec17f517ec.png)

**Comment by ippudo** [comment]
No longer an issue
