### ISSUE TITLE
?Possibly Issue 2 from google doc still unresolved? 

### ISSUE THREAD

**Issue by soshochang** [bodhiproject/bodhi-ui#996]
Is branch 819-820-qrypto features deployed on dev.puti.io ?
If not, then can prob ignore this issue.

***
Issue 2 isnt fixed for me when Im running qrypto master w/ dev.puti.io - "When user account balance changes on qrypto, dev.puti.io does not reflect the new account balance. For instance on the place bet page, the address field shows the account balance and BOT balance. If a user sends 3 QTUM, their account balance will change on qrypto,  but not on dev.puti.io"

https://docs.google.com/document/d/1iKcoC0E3mX39rt_KkW5p35eBu4i-5RVnSR2GeMZar44/edit

**Comment by dwalintukan** [comment]
@soshochang The current live version of dev puti is the old one still. I was waiting on the PR reviews and merge to master before deploying again.

**Comment by dwalintukan** [comment]
Closing for now. Reopen if the issue persists.
